// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcdxsf0D98aBxVArz4xCUc3tm3Cl9NxU',
    appId: '1:351318719019:web:115d29d3eae531962d886e',
    messagingSenderId: '351318719019',
    projectId: 'lander-ac66f',
    storageBucket: 'lander-ac66f.appspot.com',
    databaseURL:
        'https://lander-ac66f-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmgiAJABv9mMqF6Q_dr9JnwJ87bjZdSI',
    appId: '1:351318719019:android:91ba5ba6cb648fe62d886e',
    messagingSenderId: '351318719019',
    projectId: 'lander-ac66f',
    storageBucket: 'lander-ac66f.appspot.com',
    databaseURL:
        'https://lander-ac66f-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyl1NZOiYHGFGGYxlhgsWDqYxTEKjg_M',
    appId: '1:351318719019:ios:b6f24c2a80aca3592d886e',
    messagingSenderId: '351318719019',
    projectId: 'lander-ac66f',
    storageBucket: 'lander-ac66f.appspot.com',
    databaseURL:
        'https://lander-ac66f-default-rtdb.asia-southeast1.firebasedatabase.app/',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMyl1NZOiYHGFGGYxlhgsWDqYxTEKjg_M',
    appId: '1:351318719019:ios:b6f24c2a80aca3592d886e',
    messagingSenderId: '351318719019',
    projectId: 'lander-ac66f',
    storageBucket: 'lander-ac66f.appspot.com',
    databaseURL:
        'https://lander-ac66f-default-rtdb.asia-southeast1.firebasedatabase.app/',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJcdxsf0D98aBxVArz4xCUc3tm3Cl9NxU',
    appId: '1:351318719019:web:6d04387ef192eda42d886e',
    messagingSenderId: '351318719019',
    projectId: 'lander-ac66f',
    storageBucket: 'lander-ac66f.appspot.com',
    databaseURL:
        'https://lander-ac66f-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
